server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    basedir: /Users/liugf
    max-threads: 2000
    min-spare-threads: 10
    accesslog:
      pattern: common
      enabled: true
      directory: logs
      prefix: jeeplus_access_log
      suffix: .log
      request-attributes-enabled: true
      rename-on-rotate: true
logging:
  level:
    root: INFO
    com.jeeplus: DEBUG
    com.baomidou: DEBUG
    org.apache.shiro.cache.ehcache.EhCacheManager: WARN
spring:
  servlet:
    multipart:
      maxFileSize:  1000MB
      maxRequestSize: 1000MB
  devtools:
    restart:
      enabled: true
  profiles:
    active: dev
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
      dynamic:
        druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
          validation-query: select 'x'
          filters: stat # 注意这个值和druid原生不一致，默认启动了stat,wall
        p6spy: false # 默认false,线上必须关闭。开发阶段可以打开调试输出mybatis语句，但是有许多莫名其妙的bug，以及严重的性能问题，所以正式环境必须关闭。
        datasource:
          master:
            username: root
            password: root
            url: jdbc:mysql://192.168.2.57:3306/gdyhsj?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
            driver-class-name: com.mysql.cj.jdbc.Driver

            #oracle database settings
#            username: monitor
#            password: monitor
#            url: jdbc:oracle:thin:@127.0.0.1:1521:helowin
#            driver-class-name: oracle.jdbc.driver.OracleDriver


            ##mssql database settings
#            username: sa
#            password: 123456
#            driver-class-name: net.sourceforge.jtds.jdbc.Driver
#            url: jdbc:jtds:sqlserver://172.16.58.128:1433/jeeplus-boot
#            testSql: SELECT 'x'


            ##pg database settings
#            username: postgres
#            password: password
#            driver-class-name: org.postgresql.Driver
#            url: jdbc:postgresql://localhost:5432/jeeplus-boot-pg
#            testSql: SELECT 'x'
# if you need use pg database , please enable this config.
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
  #spring-ehcache的配置
  cache:
    type: ehcache # redis/ehcache， 在这里设置你使用的缓存框架，如果不想使用redis，请改成ehcache
  ehcache:
    config: classpath:ehcache.xml
  redis:
    host: localhost
    port: 6379
    expireTime: 3600000 #单位秒
  mvc.servlet.load-on-startup: 1
  jmx:
    enabled: false
# quartz任务配置
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
    jobStore:
      class: org.quartz.impl.jdbcjobstore.JobStoreTX
      driverDelegateClass: spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=
      tablePrefix: QRTZ_
      isClustered: false # 打开集群配置
      clusterCheckinInterval: 2000 # 设置集群检查间隔20s
      useProperties: false
    threadPool:
      class: org.quartz.simpl.SimpleThreadPool
      threadCount: 10
      threadPriority: 5
      threadsInheritContextClassLoaderOfInitializingThread: true

#mybatis的配置
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath*:com/jeeplus/modules/**/*Mapper.xml
  type-aliases-package: com.jeeplus.modules

beetlsql:
  enabled: false

#============================#
#===== System settings ======#
#============================#

#产品信息设置
copyrightYear: 2019
version: springboot2.0
#演示模式: 不能操作和保存的模块： sys
demoMode: false
#管理基础路径, 需同步修改：web.xml
adminPath: /a
#前端基础路径
frontPath: /f
#网站URL后缀
urlSuffix: .html
#分页配置
page.pageSize: 10
#静态文件后缀
web.staticFile: .css,.js,.png,.jpg,.gif,.jpeg,.bmp,.ico,.swf,.psd,.htc,.htm,.html,.crx,.xpi,.exe,.ipa,.apk
projectPath:
#上传文件绝对路径, 路径中不允许包含“userfiles”
userfiles.basedir:


 #===============================#
 #====== 产品信息 ================#
 #===============================#

# 产品授权
productId:
license:


#=======================================================================#
#===== plugin设置 =====#
#Plugin插件会读取该core和admin包下的基础类，如果修改了路径或者类名，请同步修改这里
#=======================================================================#
plugin:
  Plugin: com.jeeplus.plugin.ExPlugin
  PluginPool: com.jeeplus.plugin.PluginPool
  Page: com.jeeplus.core.persistence.Page
  User: com.jeeplus.modules.sys.entity.User
  Area: com.jeeplus.modules.sys.entity.Area
  Office: com.jeeplus.modules.sys.entity.Office
  DictUtils: com.jeeplus.modules.sys.utils.DictUtils
  UserUtils: com.jeeplus.modules.sys.utils.UserUtils



